// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AddPetData, AddPetErrors, AddPetResponses, CreateUserData, CreateUserErrors, CreateUserResponses, CreateUsersWithListInputData, CreateUsersWithListInputErrors, CreateUsersWithListInputResponses, DeleteOrderData, DeleteOrderErrors, DeleteOrderResponses, DeletePetData, DeletePetErrors, DeletePetResponses, DeleteUserData, DeleteUserErrors, DeleteUserResponses, FindPetsByStatusData, FindPetsByStatusErrors, FindPetsByStatusResponses, FindPetsByTagsData, FindPetsByTagsErrors, FindPetsByTagsResponses, GetInventoryData, GetInventoryErrors, GetInventoryResponses, GetOrderByIdData, GetOrderByIdErrors, GetOrderByIdResponses, GetPetByIdData, GetPetByIdErrors, GetPetByIdResponses, GetUserByNameData, GetUserByNameErrors, GetUserByNameResponses, LoginUserData, LoginUserErrors, LoginUserResponses, LogoutUserData, LogoutUserErrors, LogoutUserResponses, PlaceOrderData, PlaceOrderErrors, PlaceOrderResponses, UpdatePetData, UpdatePetErrors, UpdatePetResponses, UpdatePetWithFormData, UpdatePetWithFormErrors, UpdatePetWithFormResponses, UpdateUserData, UpdateUserErrors, UpdateUserResponses, UploadFileData, UploadFileErrors, UploadFileResponses } from './types.gen';
import { zAddPetBody, zAddPetResponse, zCreateUserBody, zCreateUserResponse, zCreateUsersWithListInputBody, zCreateUsersWithListInputResponse, zDeleteOrderPath, zDeletePetHeaders, zDeletePetPath, zDeleteUserPath, zFindPetsByStatusQuery, zFindPetsByStatusResponse, zFindPetsByTagsQuery, zFindPetsByTagsResponse, zGetInventoryResponse, zGetOrderByIdPath, zGetOrderByIdResponse, zGetPetByIdPath, zGetPetByIdResponse, zGetUserByNamePath, zGetUserByNameResponse, zLoginUserQuery, zLoginUserResponse, zPlaceOrderBody, zPlaceOrderResponse, zUpdatePetBody, zUpdatePetResponse, zUpdatePetWithFormPath, zUpdatePetWithFormQuery, zUpdatePetWithFormResponse, zUpdateUserBody, zUpdateUserPath, zUploadFileBody, zUploadFilePath, zUploadFileQuery, zUploadFileResponse } from './zod.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Add a new pet to the store.
 *
 * Add a new pet to the store.
 */
export const addPet = <ThrowOnError extends boolean = true>(options: Options<AddPetData, ThrowOnError>) => (options.client ?? client).post<AddPetResponses, AddPetErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: zAddPetBody,
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zAddPetResponse.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/pet',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Update an existing pet.
 *
 * Update an existing pet by Id.
 */
export const updatePet = <ThrowOnError extends boolean = true>(options: Options<UpdatePetData, ThrowOnError>) => (options.client ?? client).put<UpdatePetResponses, UpdatePetErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: zUpdatePetBody,
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zUpdatePetResponse.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/pet',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Finds Pets by status.
 *
 * Multiple status values can be provided with comma separated strings.
 */
export const findPetsByStatus = <ThrowOnError extends boolean = true>(options: Options<FindPetsByStatusData, ThrowOnError>) => (options.client ?? client).get<FindPetsByStatusResponses, FindPetsByStatusErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: z.never().optional(),
        query: zFindPetsByStatusQuery
    }).parseAsync(data),
    responseValidator: async (data) => await zFindPetsByStatusResponse.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/pet/findByStatus',
    ...options
});

/**
 * Finds Pets by tags.
 *
 * Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
 */
export const findPetsByTags = <ThrowOnError extends boolean = true>(options: Options<FindPetsByTagsData, ThrowOnError>) => (options.client ?? client).get<FindPetsByTagsResponses, FindPetsByTagsErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: z.never().optional(),
        query: zFindPetsByTagsQuery
    }).parseAsync(data),
    responseValidator: async (data) => await zFindPetsByTagsResponse.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/pet/findByTags',
    ...options
});

/**
 * Deletes a pet.
 *
 * Delete a pet.
 */
export const deletePet = <ThrowOnError extends boolean = true>(options: Options<DeletePetData, ThrowOnError>) => (options.client ?? client).delete<DeletePetResponses, DeletePetErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        headers: zDeletePetHeaders.optional(),
        path: zDeletePetPath,
        query: z.never().optional()
    }).parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/pet/{petId}',
    ...options
});

/**
 * Find pet by ID.
 *
 * Returns a single pet.
 */
export const getPetById = <ThrowOnError extends boolean = true>(options: Options<GetPetByIdData, ThrowOnError>) => (options.client ?? client).get<GetPetByIdResponses, GetPetByIdErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: zGetPetByIdPath,
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zGetPetByIdResponse.parseAsync(data),
    security: [{ name: 'api_key', type: 'apiKey' }, { scheme: 'bearer', type: 'http' }],
    url: '/pet/{petId}',
    ...options
});

/**
 * Updates a pet in the store with form data.
 *
 * Updates a pet resource based on the form data.
 */
export const updatePetWithForm = <ThrowOnError extends boolean = true>(options: Options<UpdatePetWithFormData, ThrowOnError>) => (options.client ?? client).post<UpdatePetWithFormResponses, UpdatePetWithFormErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: zUpdatePetWithFormPath,
        query: zUpdatePetWithFormQuery.optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zUpdatePetWithFormResponse.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/pet/{petId}',
    ...options
});

/**
 * Uploads an image.
 *
 * Upload image of the pet.
 */
export const uploadFile = <ThrowOnError extends boolean = true>(options: Options<UploadFileData, ThrowOnError>) => (options.client ?? client).post<UploadFileResponses, UploadFileErrors, ThrowOnError>({
    bodySerializer: null,
    requestValidator: async (data) => await z.object({
        body: zUploadFileBody.optional(),
        path: zUploadFilePath,
        query: zUploadFileQuery.optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zUploadFileResponse.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/pet/{petId}/uploadImage',
    ...options,
    headers: {
        'Content-Type': 'application/octet-stream',
        ...options.headers
    }
});

/**
 * Returns pet inventories by status.
 *
 * Returns a map of status codes to quantities.
 */
export const getInventory = <ThrowOnError extends boolean = true>(options?: Options<GetInventoryData, ThrowOnError>) => (options?.client ?? client).get<GetInventoryResponses, GetInventoryErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zGetInventoryResponse.parseAsync(data),
    security: [{ name: 'api_key', type: 'apiKey' }],
    url: '/store/inventory',
    ...options
});

/**
 * Place an order for a pet.
 *
 * Place a new order in the store.
 */
export const placeOrder = <ThrowOnError extends boolean = true>(options?: Options<PlaceOrderData, ThrowOnError>) => (options?.client ?? client).post<PlaceOrderResponses, PlaceOrderErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: zPlaceOrderBody.optional(),
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zPlaceOrderResponse.parseAsync(data),
    url: '/store/order',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Delete purchase order by identifier.
 *
 * For valid response try integer IDs with value < 1000. Anything above 1000 or non-integers will generate API errors.
 */
export const deleteOrder = <ThrowOnError extends boolean = true>(options: Options<DeleteOrderData, ThrowOnError>) => (options.client ?? client).delete<DeleteOrderResponses, DeleteOrderErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: zDeleteOrderPath,
        query: z.never().optional()
    }).parseAsync(data),
    url: '/store/order/{orderId}',
    ...options
});

/**
 * Find purchase order by ID.
 *
 * For valid response try integer IDs with value <= 5 or > 10. Other values will generate exceptions.
 */
export const getOrderById = <ThrowOnError extends boolean = true>(options: Options<GetOrderByIdData, ThrowOnError>) => (options.client ?? client).get<GetOrderByIdResponses, GetOrderByIdErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: zGetOrderByIdPath,
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zGetOrderByIdResponse.parseAsync(data),
    url: '/store/order/{orderId}',
    ...options
});

/**
 * Create user.
 *
 * This can only be done by the logged in user.
 */
export const createUser = <ThrowOnError extends boolean = true>(options?: Options<CreateUserData, ThrowOnError>) => (options?.client ?? client).post<CreateUserResponses, CreateUserErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: zCreateUserBody.optional(),
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zCreateUserResponse.parseAsync(data),
    url: '/user',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Creates list of users with given input array.
 *
 * Creates list of users with given input array.
 */
export const createUsersWithListInput = <ThrowOnError extends boolean = true>(options?: Options<CreateUsersWithListInputData, ThrowOnError>) => (options?.client ?? client).post<CreateUsersWithListInputResponses, CreateUsersWithListInputErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: zCreateUsersWithListInputBody.optional(),
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zCreateUsersWithListInputResponse.parseAsync(data),
    url: '/user/createWithList',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Logs user into the system.
 *
 * Log into the system.
 */
export const loginUser = <ThrowOnError extends boolean = true>(options?: Options<LoginUserData, ThrowOnError>) => (options?.client ?? client).get<LoginUserResponses, LoginUserErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: z.never().optional(),
        query: zLoginUserQuery.optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zLoginUserResponse.parseAsync(data),
    url: '/user/login',
    ...options
});

/**
 * Logs out current logged in user session.
 *
 * Log user out of the system.
 */
export const logoutUser = <ThrowOnError extends boolean = true>(options?: Options<LogoutUserData, ThrowOnError>) => (options?.client ?? client).get<LogoutUserResponses, LogoutUserErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    url: '/user/logout',
    ...options
});

/**
 * Delete user resource.
 *
 * This can only be done by the logged in user.
 */
export const deleteUser = <ThrowOnError extends boolean = true>(options: Options<DeleteUserData, ThrowOnError>) => (options.client ?? client).delete<DeleteUserResponses, DeleteUserErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: zDeleteUserPath,
        query: z.never().optional()
    }).parseAsync(data),
    url: '/user/{username}',
    ...options
});

/**
 * Get user by user name.
 *
 * Get user detail based on username.
 */
export const getUserByName = <ThrowOnError extends boolean = true>(options: Options<GetUserByNameData, ThrowOnError>) => (options.client ?? client).get<GetUserByNameResponses, GetUserByNameErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: zGetUserByNamePath,
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zGetUserByNameResponse.parseAsync(data),
    url: '/user/{username}',
    ...options
});

/**
 * Update user resource.
 *
 * This can only be done by the logged in user.
 */
export const updateUser = <ThrowOnError extends boolean = true>(options: Options<UpdateUserData, ThrowOnError>) => (options.client ?? client).put<UpdateUserResponses, UpdateUserErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: zUpdateUserBody.optional(),
        path: zUpdateUserPath,
        query: z.never().optional()
    }).parseAsync(data),
    url: '/user/{username}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
