// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zOrder = z.object({
    id: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    petId: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    quantity: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    shipDate: z.iso.datetime().optional(),
    status: z.enum([
        'placed',
        'approved',
        'delivered'
    ]).optional(),
    complete: z.boolean().optional()
});

export const zCategory = z.object({
    id: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    name: z.string().optional()
});

export const zUser = z.object({
    id: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    username: z.string().optional(),
    firstName: z.string().optional(),
    lastName: z.string().optional(),
    email: z.string().optional(),
    password: z.string().optional(),
    phone: z.string().optional(),
    userStatus: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional()
});

export const zTag = z.object({
    id: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    name: z.string().optional()
});

export const zPet = z.object({
    id: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    name: z.string(),
    category: zCategory.optional(),
    photoUrls: z.array(z.string()),
    tags: z.array(zTag).optional(),
    status: z.enum([
        'available',
        'pending',
        'sold'
    ]).optional()
});

export const zApiResponse = z.object({
    code: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    type: z.string().optional(),
    message: z.string().optional()
});

export const zPet2 = zPet;

/**
 * List of user object
 */
export const zUserArray = z.array(zUser);

/**
 * Create a new pet in the store
 */
export const zAddPetBody = zPet;

/**
 * Successful operation
 */
export const zAddPetResponse = zPet;

/**
 * Update an existent pet in the store
 */
export const zUpdatePetBody = zPet;

/**
 * Successful operation
 */
export const zUpdatePetResponse = zPet;

export const zFindPetsByStatusQuery = z.object({
    status: z.enum([
        'available',
        'pending',
        'sold'
    ]).default('available')
});

/**
 * successful operation
 */
export const zFindPetsByStatusResponse = z.array(zPet);

export const zFindPetsByTagsQuery = z.object({
    tags: z.array(z.string())
});

/**
 * successful operation
 */
export const zFindPetsByTagsResponse = z.array(zPet);

export const zDeletePetHeaders = z.object({
    api_key: z.string().optional()
});

export const zDeletePetPath = z.object({
    petId: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })
});

export const zGetPetByIdPath = z.object({
    petId: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })
});

/**
 * successful operation
 */
export const zGetPetByIdResponse = zPet;

export const zUpdatePetWithFormPath = z.object({
    petId: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })
});

export const zUpdatePetWithFormQuery = z.object({
    name: z.string().optional(),
    status: z.string().optional()
});

/**
 * successful operation
 */
export const zUpdatePetWithFormResponse = zPet;

export const zUploadFileBody = z.string();

export const zUploadFilePath = z.object({
    petId: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })
});

export const zUploadFileQuery = z.object({
    additionalMetadata: z.string().optional()
});

/**
 * successful operation
 */
export const zUploadFileResponse = zApiResponse;

/**
 * successful operation
 */
export const zGetInventoryResponse = z.record(z.string(), z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }));

export const zPlaceOrderBody = zOrder;

/**
 * successful operation
 */
export const zPlaceOrderResponse = zOrder;

export const zDeleteOrderPath = z.object({
    orderId: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })
});

export const zGetOrderByIdPath = z.object({
    orderId: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })
});

/**
 * successful operation
 */
export const zGetOrderByIdResponse = zOrder;

/**
 * Created user object
 */
export const zCreateUserBody = zUser;

/**
 * successful operation
 */
export const zCreateUserResponse = zUser;

export const zCreateUsersWithListInputBody = z.array(zUser);

/**
 * Successful operation
 */
export const zCreateUsersWithListInputResponse = zUser;

export const zLoginUserQuery = z.object({
    username: z.string().optional(),
    password: z.string().optional()
});

/**
 * successful operation
 */
export const zLoginUserResponse = z.string();

export const zDeleteUserPath = z.object({
    username: z.string()
});

export const zGetUserByNamePath = z.object({
    username: z.string()
});

/**
 * successful operation
 */
export const zGetUserByNameResponse = zUser;

/**
 * Update an existent user in the store
 */
export const zUpdateUserBody = zUser;

export const zUpdateUserPath = z.object({
    username: z.string()
});
