import type { Metadata } from 'next';

import { SiteHeader } from '@/components/site-header';
import { DocsSection } from '@/components/docs-section';
import { Footer } from '@/components/footer';
import { DOCS } from '@/lib/docs';
import { createPageMetadata } from '@/lib/site';

const page = DOCS['hey-api'];

export const metadata: Metadata = createPageMetadata({
  path: page.path,
  title: `${page.title} — tayori`,
  description: 'Use tayori with the SDK generated by Hey API from your OpenAPI specification: setup, useData, useMutation, useInfinite, prefetching, cache tags and server-side rendering with Next.js.'
});

export default function HeyApiDocsPage() {
  return (
    <>
      <SiteHeader current="hey-api" />
      <DocsSection slug="hey-api" />
      <Footer />
    </>
  );
}
